### ISSUE TITLE
Error message when loading "normal" SBML

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-lib-param-bn#19]
When opening a "normal" SBML model, the error is "not found list of qualitative species". Ideally, we should warn that the model is not SBML-qual, just SBML.

Another option would be to opportunistically import a regulatory graph from the original SBML model. We might want to consider this in the future.

**Comment by daemontus** [comment]
For now, this is fixed in c94317aafde141f89afa94245b2bb9245a3f532a by adding a more helpful error message.

Automatic parsing of non-qual SBML models is currently out of scope (there are other tools that can do the conversion to a BN though: maybe integrate these?)

**Comment by xtrojak** [comment]
Maybe [CASQ](https://gitlab.inria.fr/soliman/casq) is related work for you, although it works for CellDesigner files (which something even more general than SBML).
