### ISSUE TITLE
Convenient generator for graph subspaces

### ISSUE THREAD

**Issue by smijeva** [sybila/biodivine-lib-param-bn#27]
Add support for a convenient specification of graph subspaces. The subspaces should be generated by fixing some variables to constant values.  E.g. `1**0*1*10**`

Yet, I do not have a clear idea of what the exact interface should look like.

Probably, it would be nice to have two options of such specification:
* Abstract (e.g. a vector of nullable bools, nulls representing free variables) - to easily automatically generate some subspaces
* Specific (e.g. a map of variable_name -> bool) - to easily fix values based on variable names (e.g. case studies)

**Comment by daemontus** [comment]
Should be largely resolved in 5525b79cfe7131e7490096b10511478bdd55113d, but feedback is very much welcome.
